### ISSUE TITLE
Custom database name, username, & password

### ISSUE THREAD

**Issue by kculmback** [JPry/vvv-base#26] opened 2017-10-09 19:45 UTC
Would love to see an option to set a custom database name, database user, and database password. Often times I'm working with repos that have a full Wordpress set up in them already and the database name/user/password have already been defined in the wp-config file. This has led to errors when provisioning and the only way I have found to fix them is by changing the settings in the wp-config file from the repository, which isn't the greatest solution.

**Comment by codepuncher** [comment] 2017-10-09 22:08
This feature is currently available under the develop branch as a global setting. Have a look at the readme in there for a bit more info.

**Comment by JPry** [comment] 2017-10-10 15:46
Thanks @codepuncher and @kculmback. I've been a bit busy lately, but I haven't forgotten about getting this into a proper release. You can indeed use the `develop` branch for the time being. This can even be specified in your [`vvv-custom.yml` file](https://varyingvagrantvagrants.org/docs/en-US/vvv-config/):

```yaml
sites:
  example:
    repo: https://github.com/JPry/vvv-base.git
    branch: develop
```

One note: I try very hard to keep the `develop` branch stable, but there might occasionally be times where it is not.

Closing this as a duplicate of #24.

**Closed as completed by JPry** 2017-10-10 15:46 UTC
